apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: vj-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: vj-app
  template:
    metadata:
      labels:
        app: vj-app
    spec:
      imagePullSecrets:
        - name: ecr-registry-key
      containers:
      - name: vj-app
        image: 487383300987.dkr.ecr.us-east-1.amazonaws.com/vj-app:327190a3255c98acd1d1eaafc25f6b72aba878f2
        ports:
        - containerPort: 9000
  strategy:
    canary:
      # These services are created below
      canaryService: vj-app-canary
      stableService: vj-app-stable
      trafficRouting:
        nginx:
          stableIngress: vj-app-ingress
      steps:
      - setWeight: 25
      - pause: {duration: 2m}  # Wait 2 mins, then go to 50%
      - setWeight: 50
      - pause: {}              # Wait for manual promotion to 100%